### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/chatgpt-tui#1]
- [x] Basic communiation with OpenAI API
- [x] Basic Layout
- [x] #2
- [ ] Save conversation to file
- [ ] CLI option with [cobra](https://github.com/spf13/cobra)
- [ ] configuration with [viper](https://github.com/spf13/viper)
- [ ] bubblezone mouse support
